### ISSUE TITLE
Included PySDNSim into related projects section at https://cloudsimplus.org

### ISSUE THREAD

**Issue by manoelcampos** [ulfaric/PySDNSim#1]
Hello @ulfaric 
I've just stumbled on your project and I'd like to congratulate to provide a way to use the features in CloudSim Plus from Python.
I couldn't find another way to contact you, so I'm opening this issue.

Your project is great and makes it easier for Python devs to carry out cloud computing simulations using CloudSim Plus. 
I've just mentioned it in the Related Projects section on CloudSim Plus official page.

If you need something that I can help with your project, please let me know. Sometimes, devs creating new tools over CloudSim Plus need specific changes in the framework to accomplish what they want.
In that case, you can contact me to discuss the changes and make them official (or just ask for help).

I've noticed that you are pointing users to download a jar file from dropbox. If that jar is just an official CloudSim Plus version, I can create a release for it and users can download the official jar.

**Comment by manoelcampos** [comment]
Which specific CloudSim Plus 7.3 version are you using?
I've just released v8.0.0. Check it out at https://github.com/cloudsimplus/cloudsimplus/releases/tag/v8.0.0

**Comment by ulfaric** [comment]
Hi

Here is the python lib I made for my research paper. It basically reads a configuration file in yaml then run it through a pre-packed Java executable.

It does introduce something new, like the concept of Service Function Chain, that is the VM will commit the Cloudlet at a given order. I also used tricks to overcome some bugs I encountered with CloudSim Plus 7.3. For example, the RAM usage is not reset to zero after cloudlet is finished sometimes.
https://pypi.org/project/PySDNSim/

I am working on a totally new simulation I built purely in python which also includes the simulation of packets going through the whole network. It is based on a discreet event simulation lib I made. I personally feel it is much more easier to use comparing to simpy.

https://pypi.org/project/Akatosh/

You are welcome to check them out. Once I finished my paper, I will publicly release my new simulation tool. :)

Best regards,
Yifei


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoelcampos** [comment]
Great, now a remember I talked about other issues and you could find the root cause. About this RAM issue, if you are interested in reporting and providing a minimal example, it would be great.

Have you changed CloudSim Plus code for your simulator?

**Comment by ulfaric** [comment]
Hi Manoel

The RAM issue always happens whenever you use a random function to generate RAM usage. The RAM usage of that VM will simply keeps as the last randomly generated value and doesn't change back to 0. If this is the last cloudlet to be scheduled on the VM.

My fix is simply add a never ending Cloudlet(using the on finish listener to put a new same Cloudlet back on to the VM) for each VM. Because I am simulating containers which must have a process that is always running. So this "deamon" cloudlet fixes the issue because it overwrites the incorrect RAM usage at the end.

The backend Java executable for PySDNSim didn't have any code changed for CloudSim Plus 7.3.

Best regards,
Yifei


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoelcampos** [comment]
About the CloudSim Plus jar, you can link you README directly to the official package on Maven Central. I don't know which 7.3 specific version you are using, but check the link for the 7.3.3 release here:

https://repo1.maven.org/maven2/org/cloudsimplus/cloudsim-plus/7.3.3/cloudsim-plus-7.3.3.jar

If you are using other version, please let me know that I release it to maven central.

**Comment by ulfaric** [comment]
Hi Manoel

I updated the readme for the python lib.

I did not wrap the whole CloudSim Plus, so that jar won't work. 😅

I make a java app with the 7.30 CloudSim and the jar is compiled from the app.

Because it is related to my current paper which I have not submitted yet. So the java repository is currently private. I will open it after the paper is submitted.

However, if you want to have look now, I can give you access by adding you as a contributor for now. 🙂

Best regards,
________________________________
From: Manoel Campos ***@***.***>
Sent: 20 March 2023 20:58
To: ulfaric/PySDNSim ***@***.***>
Cc: ulfaric ***@***.***>; Mention ***@***.***>
Subject: [ulfaric/PySDNSim] Included PySDNSim into related projects section at https://cloudsimplus.org (Issue #1)


Hello @ulfaric<https://kor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fulfaric&data=05%7C01%7C%7Cc1771eea6d6c4179723308db2942bfe5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638149138891062532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZG8loqtuxMj47zXmAX%2BTEsseiBPtpsF3dPUEElaoYqc%3D&reserved=0>
I've stumbled on your project and I'd like to congratulate to provide a way to use the features in CloudSim Plus from Python.
I couldn't find another way to contact you, so I'm opening this issue.

Your project is great and makes it easier for Python devs to carry out cloud computing simulations using CloudSim Plus.
I've just mentioned it in the Related Projects section on CloudSim Plus official page.

If you need something that I can help with your project, please let me know. Sometimes, devs creating new tools over CloudSim Plus need specific changes in the framework to accomplish what they want.
In that case, you can contact me to discuss the changes and make them official (or just ask for help).

I've noticed that you are pointing users to download a jar file from dropbox. If that jar is just an official CloudSim Plus version, I can create a release for it and users can download the official jar.

**Comment by manoelcampos** [comment]
You can add me and I take a look. Best regards.
